import { z } from 'zod';
export declare const ConfigSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    HOST: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["fatal", "error", "warn", "info", "debug", "trace"]>>;
    GEMINI_API_KEY: z.ZodOptional<z.ZodString>;
    GEMINI_MODEL: z.ZodDefault<z.ZodString>;
    WHATSAPP_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    WHATSAPP_PHONE_NUMBER_ID: z.ZodOptional<z.ZodString>;
    WHATSAPP_BUSINESS_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    WHATSAPP_VERIFY_TOKEN: z.ZodOptional<z.ZodString>;
    WHATSAPP_APP_SECRET: z.ZodOptional<z.ZodString>;
    SUPABASE_URL: z.ZodOptional<z.ZodString>;
    SUPABASE_ANON_KEY: z.ZodOptional<z.ZodString>;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodOptional<z.ZodString>;
    TAVILY_API_KEY: z.ZodOptional<z.ZodString>;
    SERPER_API_KEY: z.ZodOptional<z.ZodString>;
    MAX_AGENT_STEPS: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_MAX_REQUESTS_PER_MINUTE: z.ZodDefault<z.ZodNumber>;
    APPROVAL_TIMEOUT_MINUTES: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    HOST: string;
    LOG_LEVEL: "fatal" | "error" | "warn" | "info" | "debug" | "trace";
    GEMINI_MODEL: string;
    MAX_AGENT_STEPS: number;
    RATE_LIMIT_MAX_REQUESTS_PER_MINUTE: number;
    APPROVAL_TIMEOUT_MINUTES: number;
    GEMINI_API_KEY?: string | undefined;
    WHATSAPP_ACCESS_TOKEN?: string | undefined;
    WHATSAPP_PHONE_NUMBER_ID?: string | undefined;
    WHATSAPP_BUSINESS_ACCOUNT_ID?: string | undefined;
    WHATSAPP_VERIFY_TOKEN?: string | undefined;
    WHATSAPP_APP_SECRET?: string | undefined;
    SUPABASE_URL?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    TAVILY_API_KEY?: string | undefined;
    SERPER_API_KEY?: string | undefined;
}, {
    NODE_ENV?: "development" | "test" | "production" | undefined;
    PORT?: number | undefined;
    HOST?: string | undefined;
    LOG_LEVEL?: "fatal" | "error" | "warn" | "info" | "debug" | "trace" | undefined;
    GEMINI_API_KEY?: string | undefined;
    GEMINI_MODEL?: string | undefined;
    WHATSAPP_ACCESS_TOKEN?: string | undefined;
    WHATSAPP_PHONE_NUMBER_ID?: string | undefined;
    WHATSAPP_BUSINESS_ACCOUNT_ID?: string | undefined;
    WHATSAPP_VERIFY_TOKEN?: string | undefined;
    WHATSAPP_APP_SECRET?: string | undefined;
    SUPABASE_URL?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    TAVILY_API_KEY?: string | undefined;
    SERPER_API_KEY?: string | undefined;
    MAX_AGENT_STEPS?: number | undefined;
    RATE_LIMIT_MAX_REQUESTS_PER_MINUTE?: number | undefined;
    APPROVAL_TIMEOUT_MINUTES?: number | undefined;
}>;
export type NexaConfig = z.infer<typeof ConfigSchema>;
export declare function loadConfig(env?: NodeJS.ProcessEnv): NexaConfig;
//# sourceMappingURL=index.d.ts.map